FROM apache/hive:3.1.3

# JAR folder
RUN mkdir -p /opt/hive/extra-jars

# JARs for S3 (over s3a://) Hive
ADD https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.6/hadoop-aws-3.3.6.jar /opt/hive/extra-jars/
ADD https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.661/aws-java-sdk-bundle-1.12.661.jar /opt/hive/extra-jars/

# HADOOP_CLASSPATH for Hive to use these jars
ENV HADOOP_CLASSPATH=/opt/hive/extra-jars/*

